"""ReportAgent - generates full investment report."""
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from backend.agents.state import AnalysisState


def _format_comparables(comparables: list) -> str:
    lines = []
    for c in comparables[:20]:
        price = f"${c.price_per_night:.0f}/night" if c.price_per_night else "N/A"
        lines.append(f"- **{c.name}** ({c.source}): {price} | [Link]({c.source_url})")
    return "\n".join(lines) if lines else "No comparables found."


def _format_expenses(exp: dict) -> str:
    lines = []
    for k, v in exp.items():
        if k != "total" and isinstance(v, (int, float)):
            lines.append(f"- {k.replace('_', ' ').title()}: ${v:,.0f}")
    lines.append(f"- **Total**: ${exp.get('total', 0):,.0f}")
    return "\n".join(lines)


def report_agent(state: AnalysisState) -> AnalysisState:
    """Generate full investment report in Markdown."""
    prop = state["property_input"]
    comparables = state.get("comparables", [])
    rate = state.get("recommended_nightly_rate", 0)
    occ = state.get("occupancy_rate", 0)
    rev = state.get("annual_revenue", 0)
    exp = state.get("expense_breakdown", {})
    noi_val = state.get("net_operating_income", 0)
    roi_pct = state.get("roi", 0)
    payback = state.get("payback_period_years", 0)
    npv_val = state.get("npv", 0)
    irr_val = state.get("irr", 0)
    projection = state.get("revenue_projection_10yr", [])
    doc_context = state.get("doc_context", "")

    units = (
        prop.number_of_cabins
        + prop.number_of_glamping_units
        + prop.number_of_rv_sites
        + prop.number_of_tent_sites
    )

    # Generate recommendation with LLM if available
    recommendation = _generate_recommendation(state)

    md = f"""# Glamping Investment Report
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## 1. Property Overview

| Field | Value |
|-------|-------|
| Address | {prop.property_address} |
| Acreage | {prop.acreage} acres |
| Cabins | {prop.number_of_cabins} |
| Glamping Units | {prop.number_of_glamping_units} |
| RV Sites | {prop.number_of_rv_sites} |
| Tent Sites | {prop.number_of_tent_sites} |
| **Total Units** | {units} |

{f"### Uploaded Document Context\\n{doc_context}\\n" if doc_context else ""}

---

## 2. Market Comparables

{_format_comparables(comparables)}

---

## 3. Pricing Analysis

| Metric | Value |
|--------|-------|
| Recommended Nightly Rate | ${rate:.2f} |
| Occupancy Estimate | {occ*100:.1f}% |

---

## 4. Occupancy Estimates

Based on comparable review activity and market type:
- **Estimated occupancy**: {occ*100:.1f}%
- Typical ranges: Tourism 55-70%, Rural 35-50%

---

## 5. Revenue Forecast

| Metric | Value |
|--------|-------|
| Annual Revenue | ${rev:,.0f} |
| Formula | {units} units × ${rate:.0f}/night × 365 × {occ*100:.0f}% |

### 10-Year Projection

| Year | Revenue | Expenses | NOI |
|------|---------|----------|-----|
"""
    for p in projection:
        md += f"| {p['year']} | ${p['revenue']:,.0f} | ${p['expenses']:,.0f} | ${p['noi']:,.0f} |\n"

    md += f"""
---

## 6. Expense Breakdown

{_format_expenses(exp)}

---

## 7. ROI Analysis

| Metric | Value |
|--------|-------|
| Net Operating Income | ${noi_val:,.0f} |
| ROI | {roi_pct}% |
| Payback Period | {payback:.1f} years |
| NPV (8% discount) | ${npv_val:,.0f} |
| IRR | {irr_val}% |

---

## 8. Investment Recommendation

{recommendation}

---

*Report generated by Glamping Market Research AI. Sources linked above.*
"""

    return {**state, "report_markdown": md, "recommendation": recommendation}


def _generate_recommendation(state: AnalysisState) -> str:
    """Use Ollama for recommendation if available."""
    roi_pct = state.get("roi", 0)
    payback = state.get("payback_period_years", 999)
    npv_val = state.get("npv", 0)

    try:
        import ollama
        from config import OLLAMA_BASE_URL, OLLAMA_MODEL

        client = ollama.Client(host=OLLAMA_BASE_URL)
        prompt = f"""Based on these investment metrics, write a 2-3 sentence investment recommendation:
- ROI: {roi_pct}%
- Payback period: {payback} years
- NPV: ${npv_val:,.0f}

Be concise and actionable. Mention risk factors if ROI is low or payback is long."""
        resp = client.generate(model=OLLAMA_MODEL, prompt=prompt)
        if resp and hasattr(resp, "response") and resp.response:
            return resp.response.strip()
    except Exception:
        pass

    # Fallback
    if roi_pct >= 10 and payback < 15:
        return "**Favorable.** ROI and payback period suggest solid investment potential. Proceed with due diligence on zoning and permits."
    elif roi_pct >= 5:
        return "**Moderate.** Returns are acceptable. Consider cost reductions or revenue optimization to improve metrics."
    else:
        return "**Cautious.** ROI is below typical targets. Review assumptions on occupancy and pricing, or consider alternative uses."
